apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: avengers
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      serviceAccountName: sa-backend
      securityContext:
        {}
      containers:
        - name: backend
          securityContext:
            {}
          image: "novarasa/app-showcase-backend-java:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actual/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actual/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend