{{- $projectName := .Values.global.config.name -}}
{{- $projectNamespace := .Values.global.config.namespace -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $projectName }}-backend
  namespace: {{ $projectNamespace }}
  labels:
    app.kubernetes.io/name: {{ $projectName }}-backend
    app.kubernetes.io/managed-by: helm3
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $projectName }}-backend